### ISSUE TITLE
Parenthesis around expressions are not generated correctly

### ISSUE THREAD

**Issue by arian** [arian/metac#25]
For example when doing:

``` c
int x = (2 + 4) % 2;
```

The generated code is:

``` c
int x = 2 + 4 % 2;
```

which has a different meaning.

**Comment by arian** [comment]
This is probably a spoofax bug: http://yellowgrass.org/issue/SpoofaxWithCore/58

**Comment by guwac** [comment]
There should be a generated parenthesise strategy, which needs to be integrated correctly. Not sure how to do this correctly in Core. But as you figured out, it is broken in Core.

**Comment by arian** [comment]
With the latest Spoofax version from http://buildfarm.metaborg.org/job/spoofax-newplugin/lastSuccessfulBuild/artifact/dist/eclipse/

> Spoofax: org.metaborg.spoofax.eclipse 1.5.0.20160103-174436-new-spoofax-plugin

This is fixed
